package com.example.SpringBootPostgresCRUD;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class SeleniumTests {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    //System.setProperty("webdriver.edge.driver", "..\\bart\\src\\test\\msedgedriver.exe");
    System.setProperty("webdriver.chrome.driver", "..\\bart\\src\\test\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Iniciar sesión")).click();
    driver.findElement(By.id("username")).sendKeys("admin1");
    driver.findElement(By.id("password")).sendKeys("4dm1n");
    driver.findElement(By.cssSelector(".container")).click();
    driver.findElement(By.id("username")).sendKeys("johnlennon@gmail.com");
    driver.findElement(By.id("password")).sendKeys("contraseña");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
  }
}
